name: CI

on:
  pull_request:
    branches:
      - canary

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install
        uses: ./.github/common-actions/install

      - name: Build project
        run: pnpm build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run tests
        run: pnpm test

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run Biome
        run: pnpm lint

  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    needs: [build, tests, lint]
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'kopexa-grc/sight'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  continuous-release:
    name: Continuous Release
    if: github.repository == 'kopexa-grc/sight'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Install
        uses: ./.github/common-actions/install

      - name: Build packages
        run: pnpm build

      - name: Release
        run: pnpx pkg-pr-new publish --compact --pnpm './packages/components/*' './packages/core/*' './packages/hooks/*' './packages/utilities/*'